/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{html,ts,tsx,js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      backgroundImage: {
        'sign-in': 'url("/src/assets/pics/mixed-lego.png")',
        'sign-up': 'url("/src/assets/pics/red-lego.png")',
        'collections-intro': 'url("/src/assets/pics/lego-museum.webp")',
      },
      fontSize: {
        'bh': '2.5rem',
      },
      colors: {
        'activefilterstext': '#757575',
        'activestep': '#828282',
        'burgundy': '#821919',
        'celllink': '#151414',
        'celllinkdarktext': '#2F2929',
        'charcoal': '#2C2828',
        'clearfilters': '#FFFFFF59',
        'condition': '#EAE8E8',
        'conditiondark': '#484747',
        'dark': '#2f2f2f',
        'darkactivefilterstext': '#A2A2A2',
        'darkbuttondisabled': '#3B3B3B',
        'darkfilters': '#2F2F2F',
        'darkfiltersbg': '#191919',
        'darkfiltersborder': '#727272',
        'darkfiltersprice': '#F9F9F959',
        'darkfilterstext': '#F9F9F9',
        'darkheader': '#F4F4F4',
        'darkstate': '#EEEEEE',
        'darkstatebg': '#FEFEFE',
        'darkstatefocus': '#1C1919',
        'filtersplaceholder': '#625F5F59',
        'filtersprice': '#5A5959',
        'filterstext': '#222020',
        'ghost': '#F8F8F8',
        'graphite': '#414141AD',
        'header': '#211C1C',
        'headerdark': '#2F2F2FFC',
        'label': '#332929',
        'legocy': '#FFD540',
        'legocy-active': '#ecc439',
        'legocy-hover': '#f5cc3c',
        'light': '#5F5F5F',
        'pagesize': '#EAEAEA',
        'pagesizehover': '#C9C9C9',
        'pagesizetext': '#373434',
        'rose': '#FFD0D0',
        'rose-2': '#FFD0D0D1',
        'silver': '#C4C4C4',
        'slate': '#3C3A3A',
        'state': '#393939',
        'step': '#D2D2D2',
        'subtitle': '#242020DB',
        'prevtext': '#222222',
        'prev': '#ADAAAA',
        'prevdark': '#5B5B5B',
      },
      dropShadow: {
        'legocy': '-1px 1px 10px 2px #52525226',
        'avatar': '0 4px 7px 0 #00000070',
      },
      keyframes: {
        slideDownAndFade: {
          from: { opacity: 0, transform: 'translateY(-2px)' },
          to: { opacity: 1, transform: 'translateY(0)' },
        },
        slideLeftAndFade: {
          from: { opacity: 0, transform: 'translateX(2px)' },
          to: { opacity: 1, transform: 'translateX(0)' },
        },
        slideUpAndFade: {
          from: { opacity: 0, transform: 'translateY(2px)' },
          to: { opacity: 1, transform: 'translateY(0)' },
        },
        slideRightAndFade: {
          from: { opacity: 0, transform: 'translateX(-2px)' },
          to: { opacity: 1, transform: 'translateX(0)' },
        },
      },
      animation: {
        slideDownAndFade: 'slideDownAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)',
        slideLeftAndFade: 'slideLeftAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)',
        slideUpAndFade: 'slideUpAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)',
        slideRightAndFade: 'slideRightAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
};
